### ISSUE TITLE
真机预览闪退 开发工具上不显示模型

### ISSUE THREAD

**Issue by FLAWING2016** [shrekuu/mp-device-orientation-control-example#1]
mac版微信开发工具模型加载不出 windows微测试 开发工具为最新版本 调试基础库2.16.0
真机预览微信直接闪退 机型华为p40 系统版本Android 10

**Comment by shrekuu** [comment]
@FLAWING2016  试试开发版工具 https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html

mac 上打开黑着是因为开发工具不支持调试 deviceMotion api. 有什么报错吗? 
真机上是否反复出现?

这边测试了小米8SE iPhone 8 Plus 正常.

**Comment by shrekuu** [comment]
@FLAWING2016  [Error: THREE.GLTFLoader: Unsupported asset. glTF versions >=2.0 are supported. Use LegacyGLTFLoader instead. ](https://github.com/wechat-miniprogram/threejs-miniprogram/issues/33 )

可能你手机上遇到的即为官方这个问题.  各方支持力度都不足, 我这边也,,,也,,无能为力^_^鸭😂
